### PR TITLE
ci: tests on pypy

### PR DESCRIPTION
**Pull request by skshetry**

### CODE REVIEW

**Comment by skshetry** [comment]
@pmrowla, do we need `pywin32`? It does not yet support Pypy.

**Comment by pmrowla** [comment]
@skshetry yes, the kombu filesystem transport requires pywin32 on windows, but they don't include as a dependency themselves (https://github.com/celery/kombu/issues/1270)

**Review by pmrowla — APPROVED** [review]
LGTM, I don't think we can get around only supporting *nix pypy for now

**Comment by skshetry** [comment]
> LGTM, I don't think we can get around only supporting *nix pypy for now

Relevant issue in pywin32: https://github.com/mhammond/pywin32/issues/1289

**Pull request merged**
